<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\PagesController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/PagesController.php';

return $this->services['App\Controller\PagesController'] = new \App\Controller\PagesController();
