<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvcUExJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvcUExJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNvcUExJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNvcUExJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNvcUExJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'NvcUExJ',
    'container.build_id' => 'fadb4641',
    'container.build_time' => 1527195748,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvcUExJ');
